#!/bin/bash

# Use xrandr to get the horizontal position of each monitor
monitors=$(xrandr --listmonitors | grep -v "Monitors" | sed  's/^.*+\([0-9]*\)+.*/\1/g')

SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
monitors=($monitors) # split to array $monitors
IFS=$SAVEIFS   # Restore IFS

for (( i=0; i<${#monitors[@]}; i++ ))
do
    # Spawn a gnome terminal in each monitor with "--full-screen"
    gnome-terminal --full-screen --geometry "1x1+${monitors[$i]}+0" -- "vikmatrixterm" &
done

# Lock the screen and wait until unlocked to kill spawned terminals
pyxtrlock; pgrep vikmatrixterm | xargs kill
